name: Tests & Lint

on:
  push:
    branches: [ main, dev, develop, improve ]
  pull_request:
    branches: [ main, dev, develop, improve ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Format check
        run: dart format --set-exit-if-changed lib test

      - name: Run tests
        run: flutter test
