name: Release (Prod)

on:
  push:
    tags:
      - 'prod@*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Create key.properties
        run: echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 -d > android/key.properties

      - name: Create signing keystore
        run: echo "${{ secrets.SIGNING_KEYSTORE }}" | base64 -d > android/app/key.jks

      - name: Build and validate APK
        run: flutter build apk --flavor production -t lib/main_production.dart --release

      # Deploy handled by Codemagic
